// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mremnrlyylwwxueobmil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yZW1ucmx5eWx3d3h1ZW9ibWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODQxOTQsImV4cCI6MjA3MDc2MDE5NH0.efej1JJ02o99wVp8imD3dfORCDKiPtaegwpHk4tf40M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});